# Task for all Master & Minion
- hosts: all
  become: true
  tasks:
        - name: Install Kubernetes, NTP, Docker
          yum: 
                name: "{{item}}"
                state: present
          with_items:
                - kubernetes
                - docker
                - ntp

# Task to configure Master
- hosts: master
  become: true
  tasks:
        - name: Install etcd
          yum:
                name: etcd
                state: present
          #stop kubectl kube-proxy etcd
        - name: stop kubectl kube-proxy etcd service
          systemd:
                name: "{{item}}"
                state: stopped
          with_items:
                - kube-apiserver
                - kube-controller-manager
                - kube-scheduler
                - etcd
          #copy config file to /etc/kubernetes
        - name: copy config file to /etc/kubernetes
          copy:
                src: "{{item.src}}"
                dest: "{{item.des}}"
                backup: yes
          with_items:
                - { src: 'ConfigFile/master/apiserver', des: '/etc/kubernetes/apiserver' }
                - { src: 'ConfigFile/master/config', des: '/etc/kubernetes/config' }
                - { src: 'ConfigFile/master/etcd.conf', des: '/etc/etcd/etcd.conf' }
          #start kubectl kube-proxy
        - name: start kubernetes and etcd services
          systemd:
                name: "{{item}}"
                state: started
          with_items:
          #enable kubectl kube-proxy
                - kube-apiserver
                - kube-controller-manager
                - kube-scheduler
                - etcd
        - name: enable kubernetes and etcd services
          systemd:
                name: "{{item}}"
                enabled: yes
          with_items:
                - kube-apiserver
                - kube-controller-manager
                - kube-scheduler
                - etcd
                - ntpd
