---
- name: restart services
  systemd:
        name: "{{ item }}"
        state: restarted
  with_items:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
        - etcd

- name: enabled services
  systemd:
        name: "{{ item }}"
        enabled: yes
  with_items:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
        - etcd
        - docker
        - ntpd

- name: start services
  systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
  with_items:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
        - etcd
        - docker
        - ntpd
