---
- name: Start and enable services  
  systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
  with_items:
        - kube-proxy
        - kubelet
        - docker
        - ntpd
