---
- name: Install Kubernetes, NTP, Docker
  yum: 
        name: "{{ item }}"
        state: present
  with_items:
        - kubernetes
        - docker
        - ntp
  notify:
        - start services

#copy config file to /etc/kubernetes
- name: copy config file to /etc/kubernetes
  copy:
        src: "{{ item.src }}"
        dest: "{{ item.des }}"
        backup: yes
  with_items:
        - { src: 'config', des: '/etc/kubernetes/config' }
- name: copy template file to /etc/kubernetes/kubelet
  template: src=../files/kubelet.j2 dest=/etc/kubernetes/kubelet
  notify:
        - restart services
- include: enableService.yaml


